name: 'Prepare Project'
description: 'Checkout and installs gradle'
runs:
  using: "composite"
  steps:

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Change wrapper permissions
      run: chmod +x ./gradlew
      shell: bash

    # Step 3: Setup Gradle with caching (speeds up subsequent builds)
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3